[target.thumbv7m-none-eabi]
# uncomment this to make `cargo run` execute programs on QEMU
runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"
# runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -gdb tcp::3333 -S -kernel"
rustflags = ["--cfg", "armv7m"]


[target.thumbv7em-none-eabihf]
# uncomment this to make `cargo run` execute programs on QEMU
runner = "qemu-system-arm -cpu cortex-m4 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"
# runner = "qemu-system-arm -cpu cortex-m4 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -gdb tcp::3333 -S -kernel"
rustflags = ["--cfg", "armv7em"]

[target.msp430-none-elf]
# Upload firmware and start a GDB session with "cargo run".
runner = "msp430-elf-gdb -q -x mspdebug.gdb"

rustflags = [
    "-C", "link-arg=-nostartfiles",
    # Between approximately version 6.4.0 and 8.3.1 (non-inclusive) of the
    # TI-provided GCC, the linker would default to linking against MSP430X
    # libraries, resulting in a failed link. It is harmless to include the
    # option though.
    "-C", "link-arg=-mcpu=msp430",
    # Multiplication routines of the form __mspabi_mpy*.
    # Uncomment _one_ of the lines below:
    # * If your msp430 does not have a multiplier, use mul_none.
    # * Use -lmul_16 for MSP430s with 16-bit hardware multiplier.
    # * Use -lmul_32 for MSP430s with 32-bit hardware multiplier
    #   _except for_ the F5-series.
    # * Use -lmul_f5 for MSP430 in the F5 series, which have both
    #   a 16-bit and 32-bit capable multiplier.
    # "-C", "link-arg=-lmul_none",
    # "-C", "link-arg=-lmul_16",
    # "-C", "link-arg=-lmul_32",
    "-C", "link-arg=-lmul_f5",

    # Provides __mspabi_remu, __mspabi_func_epilog_{1,7}, etc. It is normal for
    # some applications to not use this library, so feel free to comment out
    # and experiment!
    "-C", "link-arg=-lgcc",
    "-C", "link-arg=-Wl,--allow-multiple-definition",
]

[build]
#target = "thumbv7m-none-eabi"
#target = "thumbv7em-none-eabihf"
target = "msp430-none-elf"
#target = "x86_64-unknown-linux-gnu"

[env]
#ENV_BOARD="QEMU"
#ENV_BOARD="APOLLO4BP"
ENV_BOARD="MSP430FR5994"
#ENV_BOARD="TEST"

[unstable]
# MSP430 doesn't come with libcore compiled already. But when it does, this
# key can be removed.
# build-std = ["core"]